### ISSUE TITLE
Error: can't parse Package.swift

### ISSUE THREAD

**Issue by TnnsBeast** [jakeheis/Ice#39]
Hi there,
I get Error: can't parse Package.swift when trying to make a new project using ice new
Is this just because it hasn't been updated for BigSur? I'm using Xcode 12.2

Thanks!

**Comment by Samasaur1** [comment]
I've been getting this for a while as well. I think it's because Ice doesn't support ` swift-tools-version` above 5.0, but I'm not sure how to fix this

**Comment by iWECon** [comment]
Same.

**Comment by jakeheis** [comment]
Swift 5.4 compatibility was added in version `0.8.3` so this should be solved!

**Comment by vktt** [comment]
I think this issue is back with updated version of Swift-tools. I am currently on 5.5 and ice does gives parsing error.
